# DOCKER_BUILDKIT=1 docker build -f docker/Dockerfile-pe -t pe --build-arg UID=$(id -u) --build-arg GID=$(id -g) .

FROM ubuntu:22.04 AS base

ARG UID
ARG GID
ARG USERNAME=hglee

RUN groupadd -g ${GID} ${USERNAME} && \
    useradd -m -u ${UID} -g ${USERNAME} ${USERNAME}

# ----------------------------------------------------------------------

# python 3.11.10
FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-devel
ARG USERNAME=hglee

# Copy only the minimal needed configuration or files.
COPY --from=base /etc/passwd /etc/passwd
COPY --from=base /etc/group /etc/group
RUN mkdir -p /home/${USERNAME} && chown ${USERNAME}:${USERNAME} /home/${USERNAME}
# Add user to sudo group
RUN usermod -aG sudo ${USERNAME}

RUN sed -i 's@archive.ubuntu.com@mirror.kakao.com@g' /etc/apt/sources.list

ENV TZ=Asia/Seoul
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install -y \
        vim git zsh htop iftop tmux unzip zip curl wget tree ncdu \
        tzdata bzip2 build-essential net-tools iputils-ping locales \
        libgl1-mesa-glx libglib2.0-0 && \
    ln -fs /usr/share/zoneinfo/$TZ /etc/localtime && \
    dpkg-reconfigure --frontend noninteractive tzdata && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean

RUN locale-gen en_US.UTF-8 && \
    locale-gen ko_KR.UTF-8 && \
    update-locale LANG=en_US.UTF-8


# Install python packages
RUN conda install -y python=3.12 --update-deps --force-reinstall
RUN pip install --no-cache-dir uv && \
    conda install -y ffmpeg -c conda-forge && \
    uv pip install --system --no-cache-dir \
        torchvision==0.20.1 torchaudio==2.5.1 xformers torchcodec==0.1 --index-url https://download.pytorch.org/whl/cu124
# RUN git clone https://github.com/facebookresearch/perception_models.git /perception_models && \
#     uv pip install --directory /perception_models --system --no-cache-dir -e .
RUN uv pip install --system --no-cache-dir \
    perception_models@git+https://github.com/facebookresearch/perception_models.git@0fc34706b2c78fc2878fd54fd05075304583b8b3 \
    pytorchvideo@git+https://github.com/facebookresearch/pytorchvideo.git@6cdc929315aab1b5674b6dcf73b16ec99147735f \
    seaborn matplotlib pandas fire tqdm jupyter ipykernel ftfy

# ----------------------------------------------------------------------

# RUN chsh -s /usr/bin/zsh ${USERNAME}
USER ${USERNAME}

WORKDIR /code

CMD ["bash"]
