name: llava-ov-7b-deepseek-r1-8b

version: '3.8'

services:
  torch_worker:
    image: torch
    volumes:
      - /projects3/home/hglee/prjs/agent-based-vad/:/code
      - $HOME/.cache:/home/hglee/.cache
      - /projects3/datasets/UCF_Crimes/:/datasets/UCF_Crimes/
    command: bash scripts/vlm_llm_ucf_eval.sh ${REPLICA_INDEX} 8 'lmms-lab/llava-onevision-qwen2-7b-ov'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
              device_ids: ['${REPLICA_INDEX}']

# for i in {0..7}; do
#     REPLICA_INDEX=$i docker-compose -f docker/docker-compose-multirun-single.yaml up -d
# done
# sudo로 docker-compose 깔아야 쓸 수 있음
